version: '3'

services:

  poll:
    build: poll/
    ports:
      - "5000:80"
    restart: on-failure
    networks:
      - poll-tier
    links:
      - redis
      - db
    depends_on:
      - redis
    environment:
      - HOST=0.0.0.0

  redis:
    image: redis:latest
    restart: on-failure
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier

  worker:
    build: worker/
    restart: on-failure
    networks:
      - back-tier
    depends_on:
      - redis
      - db
    environment:
      - HOST=0.0.0.0

  db:
    image: postgres:13.0
    restart: on-failure
    networks:
      - result-tier
      - back-tier
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

  result:
    build: result/
    restart: on-failure
    ports:
      - "5001:80"
    networks:
      - result-tier
    depends_on:
      - db
    environment:
      - HOST=0.0.0.0
      - PORT: 80

volumes:
  db-data:

networks:
  poll-tier:
  result-tier:
  back-tier: